#
# Copyright (c) 2026 Nordic Semiconductor ASA
#
# SPDX-License-Identifier: LicenseRef-Nordic-5-Clause
#

CONFIG_GPIO=y

CONFIG_BOOT_BANNER=n
CONFIG_NCS_BOOT_BANNER=n

CONFIG_LOG=n
CONFIG_CONSOLE=n
CONFIG_UART_CONSOLE=n
CONFIG_SERIAL=n
CONFIG_PRINTK=n

CONFIG_MAIN_STACK_SIZE=840
CONFIG_ISR_STACK_SIZE=1536
CONFIG_SYSTEM_CLOCK_NO_WAIT=y

CONFIG_HW_STACK_PROTECTION=n

CONFIG_SIZE_OPTIMIZATIONS=y
