#
# Copyright (c) 2023 Nordic Semiconductor
#
# SPDX-License-Identifier: LicenseRef-Nordic-5-Clause
#

if(SB_CONFIG_BOOTLOADER_MCUBOOT)
  get_target_property(mcuboot_board mcuboot BOARD)

  if(((NOT ${ZCMAKE_APPLICATION}_BOARD) AND (NOT mcuboot_board)) OR
     ("${${ZCMAKE_APPLICATION}_BOARD}" STREQUAL "${mcuboot_board}"))
    set_config_bool(${image} CONFIG_NCS_MCUBOOT_IN_BUILD y)
  endif()
endif()


if(SB_CONFIG_SECURE_BOOT_APPCORE)
  if(NOT DEFINED b0_BOARD AND DEFINED board_target_secure)
    # b0 must run in secure mode on the nRF9160/nRF5340
    set_target_properties(b0 PROPERTIES BOARD ${board_target_secure})
  endif()

  # Apply configuration for hashing
  if(SB_CONFIG_SECURE_BOOT_HASH_TYPE_SHA256 AND NOT SB_CONFIG_SECURE_BOOT_APPCORE_HASH_TYPE_NONE)
    if(SB_CONFIG_SECURE_BOOT_APPCORE_HASH_TYPE_HARDWARE)
      set_config_bool(b0 CONFIG_SB_CRYPTO_CC310_SHA256 y)
    elseif(SB_CONFIG_SECURE_BOOT_APPCORE_HASH_TYPE_SOFTWARE)
      set_config_bool(b0 CONFIG_SB_CRYPTO_OBERON_SHA256 y)
    elseif(SB_CONFIG_SECURE_BOOT_APPCORE_HASH_TYPE_UNUSED)
      set_config_bool(b0 CONFIG_SB_CRYPTO_NO_SHA256 y)
    endif()
  elseif(SB_CONFIG_SECURE_BOOT_HASH_TYPE_NONE OR SB_CONFIG_SECURE_BOOT_APPCORE_HASH_TYPE_NONE)
    set_config_bool(b0 CONFIG_SB_CRYPTO_NONE y)
  endif()

  if(SB_CONFIG_SECURE_BOOT_SIGNATURE_TYPE_ED25519)
    if(SB_CONFIG_SECURE_BOOT_APPCORE_SIGNATURE_TYPE_HARDWARE)
      set_config_bool(b0 CONFIG_NRF_SECURITY y)
      set_config_bool(b0 CONFIG_SB_CRYPTO_PSA_ED25519 y)
    endif()
  elseif(SB_CONFIG_SECURE_BOOT_SIGNATURE_TYPE_ECDSA)
    if(SB_CONFIG_SECURE_BOOT_APPCORE_SIGNATURE_TYPE_HARDWARE)
      set_config_bool(b0 CONFIG_SB_CRYPTO_CC310_ECDSA_SECP256R1 y)
    elseif(SB_CONFIG_SECURE_BOOT_APPCORE_SIGNATURE_TYPE_SOFTWARE)
      set_config_bool(b0 CONFIG_SB_CRYPTO_OBERON_ECDSA_SECP256R1 y)
    elseif(SB_CONFIG_SECURE_BOOT_APPCORE_SIGNATURE_TYPE_UNUSED)
      set_config_bool(b0 CONFIG_SB_CRYPTO_NO_ECDSA_SECP256R1 y)
    endif()
  endif()
endif()

if(SB_CONFIG_SECURE_BOOT_NETCORE)
  # Apply configuration for hashing
  if(SB_CONFIG_SECURE_BOOT_HASH_TYPE_SHA256 AND NOT SB_CONFIG_SECURE_BOOT_NETCORE_HASH_TYPE_NONE)
    if(SB_CONFIG_SECURE_BOOT_NETCORE_HASH_TYPE_SOFTWARE)
      set_config_bool(b0n CONFIG_SB_CRYPTO_OBERON_SHA256 y)
    elseif(SB_CONFIG_SECURE_BOOT_NETCORE_HASH_TYPE_UNUSED)
      set_config_bool(b0n CONFIG_SB_CRYPTO_NO_SHA256 y)
    endif()
  elseif(SB_CONFIG_SECURE_BOOT_HASH_TYPE_NONE OR SB_CONFIG_SECURE_BOOT_NETCORE_HASH_TYPE_NONE)
    set_config_bool(b0n CONFIG_SB_CRYPTO_NONE y)
  endif()

  if(SB_CONFIG_SECURE_BOOT_SIGNATURE_TYPE_ECDSA)
    if(SB_CONFIG_SECURE_BOOT_NETCORE_SIGNATURE_TYPE_SOFTWARE)
      set_config_bool(b0n CONFIG_SB_CRYPTO_OBERON_ECDSA_SECP256R1 y)
    elseif(SB_CONFIG_SECURE_BOOT_NETCORE_SIGNATURE_TYPE_UNUSED)
      set_config_bool(b0n CONFIG_SB_CRYPTO_NO_ECDSA_SECP256R1 y)
    endif()
  endif()
endif()

if(SB_CONFIG_CRACEN_MICROCODE_LOAD_ONCE)
  if(SB_CONFIG_CRACEN_MICROCODE_LOAD_B0)
    set_config_bool(b0 CONFIG_CRACEN_LOAD_MICROCODE y)
  elseif(SB_CONFIG_CRACEN_MICROCODE_LOAD_MCUBOOT)
    if(SB_CONFIG_SECURE_BOOT_APPCORE)
      set_config_bool(b0 CONFIG_CRACEN_LOAD_MICROCODE n)
    endif()
  endif()
endif()
